baseURL = "/"
title = "cohsh's blog"
theme = "m10c"
paginate = 8
relativeURLs = true

languageCode = "ja-jp"
hasCJKLanguage = true

staticDir = "static"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[permalinks]
post = "/:year/:filename"

[taxonomies]
tag = "tags"
archive = "archives"

[params]
author = "Kohei Ishii"
description = "Ph.D. Student at The University of Tokyo"
avatar = "/avatar.png"

[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/cohsh"

[[params.social]]
icon = "twitter"
name = "Twitter"
url = "https://twitter.com/cohsh_"

[[params.social]]
icon = "instagram"
name = "Instagram"
url = "https://instagram.com/cohsh_"

[[params.social]]
icon = ""
name = "Website"
url = "https://cohsh.github.io"

[params.style]
  darkestColor = "#322C28" # https://irocore.com/kurotsurubami/
  darkColor = "#595045" # https://irocore.com/keshizumi-iro/
  lightColor = "#FDFCF5" # https://irocore.com/shirayuri-iro/
  lightestColor = "#FFFFFC" # https://irocore.com/gofun-iro/
  primaryColor = "#6CBB5A" # https://irocore.com/senryoku/
